<?php

namespace App\Http\Controllers\Leader;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use App\Models\Payment;
use PDF;

class ReportController extends Controller
{
    public function generateGeneralReport(Request $request)
    {
    try {
        \Log::info('Generating general report...');
        
<<<<<<< HEAD
        // Get statistics (excluding user ID 16)
        $totalUsers = User::where('id', '!=', 16)->count();
=======
        // Get statistics
        $totalUsers = User::count();
>>>>>>> d02097e78921f07047de1659e70e5f3e619d0429
        $totalPayments = Payment::where('status', 'completed')->sum('amount');
        $pendingPayments = Payment::where('status', 'pending')->count();
        $completedPayments = Payment::where('status', 'completed')->count();
        
        \Log::info('Stats: users=' . $totalUsers . ', payments=' . $totalPayments);
        
        // Get payment details for report
        $payments = Payment::with('user')
            ->where('status', 'completed')
            ->orderBy('created_at', 'desc')
            ->get();
        
        // Create PDF using FPDF
        require_once base_path('fpdf186/fpdf.php');
        
        $pdf = new \FPDF();
        $pdf->AddPage();
        
        // Set font for header
        $pdf->SetFont('Times', 'B', 16);
        $pdf->SetTextColor(0, 0, 0);
        
        // Main title
        $pdf->Cell(0, 10, 'TMCS SYSTEM - GENERAL PAYMENT REPORT', 0, 1, 'C');
        $pdf->Ln(5);
        
        // Report metadata
        $pdf->SetFont('Times', '', 10);
        $pdf->Cell(0, 6, 'Generated on: ' . date('Y-m-d H:i:s'), 0, 0, 'L');
        $pdf->Cell(0, 6, 'Generated by: ' . Auth::user()->name, 0, 1, 'R');
        $pdf->Cell(0, 6, 'Report ID: TMCS-GR-' . date('YmdHis'), 0, 1, 'L');
        $pdf->Ln(10);
        
        // Statistics Summary Header
        $pdf->SetFont('Times', 'B', 12);
        $pdf->SetFillColor(52, 152, 219);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->Cell(0, 8, 'STATISTICS SUMMARY', 0, 1, 'L', true);
        $pdf->Ln(10);
        
        // Statistics Cards Layout
        $pdf->SetTextColor(0, 0, 0);
        $cardWidth = 45;
        $cardHeight = 30;
        $spacing = 5;
        $startX = 10;
        $startY = $pdf->GetY();
        
        // Card 1: Total Users
        $pdf->SetFillColor(52, 152, 219);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->Rect($startX, $startY, $cardWidth, $cardHeight, 'F');
        $pdf->SetFont('Times', 'B', 10);
        $pdf->SetXY($startX, $startY + 5);
        $pdf->Cell($cardWidth, 8, 'Total Users', 0, 1, 'C');
        $pdf->SetFont('Times', 'B', 14);
        $pdf->SetXY($startX, $startY + 15);
        $pdf->Cell($cardWidth, 8, number_format($totalUsers), 0, 1, 'C');
        
        // Card 2: Total Payments
        $startX += $cardWidth + $spacing;
        $pdf->SetFillColor(46, 204, 113);
        $pdf->Rect($startX, $startY, $cardWidth, $cardHeight, 'F');
        $pdf->SetFont('Times', 'B', 10);
        $pdf->SetXY($startX, $startY + 5);
        $pdf->Cell($cardWidth, 8, 'Total Payments', 0, 1, 'C');
        $pdf->SetFont('Times', 'B', 14);
        $pdf->SetXY($startX, $startY + 15);
        $pdf->Cell($cardWidth, 8, 'Tshs ' . number_format($totalPayments, 2), 0, 1, 'C');
        
        // Card 3: Pending Payments
        $startX += $cardWidth + $spacing;
        $pdf->SetFillColor(241, 196, 15);
        $pdf->Rect($startX, $startY, $cardWidth, $cardHeight, 'F');
        $pdf->SetFont('Times', 'B', 10);
        $pdf->SetXY($startX, $startY + 5);
        $pdf->Cell($cardWidth, 8, 'Pending', 0, 1, 'C');
        $pdf->SetFont('Times', 'B', 14);
        $pdf->SetXY($startX, $startY + 15);
        $pdf->Cell($cardWidth, 8, number_format($pendingPayments), 0, 1, 'C');
        
        // Card 4: Completed Payments
        $startX += $cardWidth + $spacing;
        $pdf->SetFillColor(155, 89, 182);
        $pdf->Rect($startX, $startY, $cardWidth, $cardHeight, 'F');
        $pdf->SetFont('Times', 'B', 10);
        $pdf->SetXY($startX, $startY + 5);
        $pdf->Cell($cardWidth, 8, 'Completed', 0, 1, 'C');
        $pdf->SetFont('Times', 'B', 14);
        $pdf->SetXY($startX, $startY + 15);
        $pdf->Cell($cardWidth, 8, number_format($completedPayments), 0, 1, 'C');
        
        // Reset position for next section
        $pdf->SetXY(10, $startY + $cardHeight + 15);
        
        // Group payments by user
        $groupedPayments = [];
        foreach ($payments as $payment) {
            $userId = $payment->user_id;
            if (!isset($groupedPayments[$userId])) {
                $groupedPayments[$userId] = [
                    'user' => $payment->user,
                    'payments' => []
                ];
            }
            $groupedPayments[$userId]['payments'][] = $payment;
        }
        
        // Payment Details Header
        $pdf->SetFont('Times', 'B', 12);
        $pdf->SetFillColor(52, 152, 219);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->Cell(0, 8, 'PAYMENT DETAILS BY USER', 0, 1, 'L', true);
        $pdf->Ln(5);
        
        // Table headers
        $pdf->SetFillColor(52, 73, 94);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('Times', 'B', 10);
        $pdf->Cell(15, 8, 'S/No', 1, 0, 'C', true);
        $pdf->Cell(35, 8, 'Amount', 1, 0, 'C', true);
        $pdf->Cell(30, 8, 'Type', 1, 0, 'C', true);
        $pdf->Cell(30, 8, 'Status', 1, 0, 'C', true);
        $pdf->Cell(35, 8, 'Date', 1, 1, 'C', true);
        
        // Display payments grouped by user
        $pdf->SetTextColor(0, 0, 0);
        $pdf->SetFont('Times', '', 9);
        $overallSerial = 1;
        $userCount = 0;
        
        foreach ($groupedPayments as $userId => $userData) {
            $userCount++;
            $user = $userData['user'];
            $userPayments = $userData['payments'];
            
            // User header
            $pdf->SetFont('Times', 'B', 11);
            $pdf->SetFillColor(230, 230, 250);
            $pdf->Cell(0, 10, 'User ' . $userCount . ': ' . $user->name . ' (' . count($userPayments) . ' payments)', 1, 1, 'L', true);
            
            // User's payments
            $pdf->SetFont('Times', '', 9);
            $paymentSerial = 1;
            
            foreach ($userPayments as $payment) {
                // Alternate row colors
                if ($paymentSerial % 2 == 0) {
                    $pdf->SetFillColor(248, 249, 250);
                } else {
                    $pdf->SetFillColor(255, 255, 255);
                }
                
                $pdf->Cell(15, 8, $paymentSerial, 1, 0, 'C', true);
                $pdf->Cell(35, 8, 'Tshs ' . number_format($payment->amount, 2), 1, 0, 'C', true);
                $pdf->Cell(30, 8, substr($payment->payment_type ?? 'N/A', 0, 12), 1, 0, 'L', true);
                $pdf->Cell(30, 8, ucfirst($payment->status), 1, 0, 'C', true);
                $pdf->Cell(35, 8, date('M d, Y', strtotime($payment->created_at)), 1, 1, 'C', true);
                $paymentSerial++;
                $overallSerial++;
            }
            
            // Add spacing between users
            $pdf->Ln(3);
        }
        
        // Minimal footer
        $pdf->SetY(-15);
        $pdf->SetTextColor(128, 128, 128); // Light gray text
        $pdf->SetFont('Times', 'I', 7);
        $pdf->Cell(0, 8, 'Generated on ' . date('Y-m-d H:i:s') . ' | TMCS System', 0, 1, 'C');
            
            // Save PDF
            $filename = 'general_report_' . date('Y-m-d_H-i-s') . '.pdf';
            $filepath = public_path('reports/' . $filename);
            
            // Create reports directory if it doesn't exist
            if (!is_dir(public_path('reports'))) {
                mkdir(public_path('reports'), 0777, true);
            }
            
            $pdf->Output('F', $filepath);
            
            \Log::info('PDF saved to: ' . $filepath);
            
            return response()->json([
                'success' => true,
                'message' => 'General report generated successfully',
                'report_url' => asset('reports/' . $filename),
                'filename' => $filename
            ]);
            
        } catch (\Exception $e) {
            \Log::error('Error generating general report: ' . $e->getMessage());
            \Log::error('Stack trace: ' . $e->getTraceAsString());
            return response()->json([
                'success' => false,
                'message' => 'Error generating report: ' . $e->getMessage()
            ], 500);
        }
    }
    
    public function exportGeneralData(Request $request)
    {
        try {
            // Get payment data
            $payments = Payment::with('user')
                ->orderBy('created_at', 'desc')
                ->get();
            
            // Create CSV
            $filename = 'TMCS_General_Payment_Report_' . date('Y-m-d_H-i-s') . '.csv';
            $filepath = public_path('reports/' . $filename);
            
            // Create reports directory if it doesn't exist
            if (!is_dir(public_path('reports'))) {
                mkdir(public_path('reports'), 0777, true);
            }
            
            $file = fopen($filepath, 'w');
            
            // Enhanced CSV headers with metadata
            fputcsv($file, ['TMCS SYSTEM - GENERAL PAYMENT REPORT']);
            fputcsv($file, ['Generated on: ' . date('Y-m-d H:i:s')]);
            fputcsv($file, ['Generated by: ' . Auth::user()->name]);
            fputcsv($file, ['Report ID: TMCS-GR-' . date('YmdHis')]);
            fputcsv($file, []); // Empty row
            
            // Statistics summary
            $totalUsers = User::count();
            $totalPayments = Payment::where('status', 'completed')->sum('amount');
            $pendingPayments = Payment::where('status', 'pending')->count();
            $completedPayments = Payment::where('status', 'completed')->count();
            
            fputcsv($file, ['STATISTICS SUMMARY']);
            fputcsv($file, ['Metric', 'Value', 'Description']);
            fputcsv($file, ['Total Users', $totalUsers, 'All registered users in the system']);
            fputcsv($file, ['Total Payments Amount', 'Tshs ' . number_format($totalPayments, 2), 'Sum of all completed payments']);
            fputcsv($file, ['Pending Payments', $pendingPayments, 'Payments awaiting approval']);
            fputcsv($file, ['Completed Payments', $completedPayments, 'Successfully processed payments']);
            fputcsv($file, []); // Empty row
            
            // Payment details headers
            fputcsv($file, ['PAYMENT DETAILS']);
            fputcsv($file, ['ID', 'User Name', 'Email', 'Amount (Tshs)', 'Payment Type', 'Status', 'Transaction Date', 'Created At']);
            
            // CSV data
            foreach ($payments as $payment) {
                fputcsv($file, [
                    $payment->id,
                    $payment->user->name ?? 'N/A',
                    $payment->user->email ?? 'N/A',
                    $payment->amount,
                    $payment->payment_type ?? 'N/A',
                    ucfirst($payment->status),
                    date('Y-m-d H:i:s', strtotime($payment->created_at)),
                    $payment->created_at
                ]);
            }
            
            // Footer
            fputcsv($file, []);
            fputcsv($file, ['END OF REPORT']);
            fputcsv($file, ['TMCS System - Official Report']);
            fputcsv($file, ['This report is confidential and intended for authorized personnel only']);
            
            fclose($file);
            
            return response()->json([
                'success' => true,
                'message' => 'General data exported successfully',
                'download_url' => asset('reports/' . $filename),
                'filename' => $filename
            ]);
            
        } catch (\Exception $e) {
            \Log::error('Error exporting general data: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Error exporting data: ' . $e->getMessage()
            ], 500);
        }
    }
    
    public function generateMemberReport(Request $request)
    {
        try {
<<<<<<< HEAD
            // Get member statistics (excluding user ID 16)
            $activeMembers = User::where('membership_status', 'Active')->where('id', '!=', 16)->count();
            $newMembers = User::where('created_at', '>=', now()->subDays(30))->where('id', '!=', 16)->count();
            $pendingMembers = User::where('membership_status', 'Pending')->where('id', '!=', 16)->count();
            $premiumMembers = User::where('membership_status', 'Premium')->where('id', '!=', 16)->count();
            
            // Get member details (excluding user ID 16)
            $members = User::where('id', '!=', 16)->orderBy('created_at', 'desc')->get();
=======
            // Get member statistics
            $activeMembers = User::where('membership_status', 'Active')->count();
            $newMembers = User::where('created_at', '>=', now()->subDays(30))->count();
            $pendingMembers = User::where('membership_status', 'Pending')->count();
            $premiumMembers = User::where('membership_status', 'Premium')->count();
            
            // Get member details
            $members = User::orderBy('created_at', 'desc')->get();
>>>>>>> d02097e78921f07047de1659e70e5f3e619d0429
            
            // Create PDF using FPDF
            require_once base_path('fpdf186/fpdf.php');
            
            $pdf = new \FPDF();
            $pdf->AddPage();
            
            // Set font for header
            $pdf->SetFont('Times', 'B', 16);
            $pdf->SetTextColor(0, 0, 0);
            
            // Main title
            $pdf->Cell(0, 10, 'TMCS SYSTEM - MEMBER ANALYTICS REPORT', 0, 1, 'C');
            $pdf->Ln(5);
            
            // Report metadata
            $pdf->SetFont('Times', '', 10);
            $pdf->Cell(0, 6, 'Generated on: ' . date('Y-m-d H:i:s'), 0, 0, 'L');
            $pdf->Cell(0, 6, 'Generated by: ' . Auth::user()->name, 0, 1, 'R');
            $pdf->Cell(0, 6, 'Report ID: TMCS-MR-' . date('YmdHis'), 0, 1, 'L');
            $pdf->Ln(10);
            
            // Member Statistics Header
            $pdf->SetFont('Times', 'B', 12);
            $pdf->SetFillColor(52, 152, 219);
            $pdf->SetTextColor(255, 255, 255);
            $pdf->Cell(0, 8, 'MEMBER STATISTICS OVERVIEW', 0, 1, 'L', true);
            $pdf->Ln(10);
            
            // Statistics Cards Layout
            $pdf->SetTextColor(0, 0, 0);
            $cardWidth = 45;
            $cardHeight = 30;
            $spacing = 5;
            $startX = 10;
            $startY = $pdf->GetY();
            
            // Card 1: Active Members
            $pdf->SetFillColor(46, 204, 113);
            $pdf->SetTextColor(255, 255, 255);
            $pdf->Rect($startX, $startY, $cardWidth, $cardHeight, 'F');
            $pdf->SetFont('Times', 'B', 10);
            $pdf->SetXY($startX, $startY + 5);
            $pdf->Cell($cardWidth, 8, 'Active', 0, 1, 'C');
            $pdf->SetFont('Times', 'B', 14);
            $pdf->SetXY($startX, $startY + 15);
            $pdf->Cell($cardWidth, 8, number_format($activeMembers), 0, 1, 'C');
            
            // Card 2: New Members
            $startX += $cardWidth + $spacing;
            $pdf->SetFillColor(52, 152, 219);
            $pdf->Rect($startX, $startY, $cardWidth, $cardHeight, 'F');
            $pdf->SetFont('Times', 'B', 10);
            $pdf->SetXY($startX, $startY + 5);
            $pdf->Cell($cardWidth, 8, 'New (30d)', 0, 1, 'C');
            $pdf->SetFont('Times', 'B', 14);
            $pdf->SetXY($startX, $startY + 15);
            $pdf->Cell($cardWidth, 8, number_format($newMembers), 0, 1, 'C');
            
            // Card 3: Pending Members
            $startX += $cardWidth + $spacing;
            $pdf->SetFillColor(241, 196, 15);
            $pdf->Rect($startX, $startY, $cardWidth, $cardHeight, 'F');
            $pdf->SetFont('Times', 'B', 10);
            $pdf->SetXY($startX, $startY + 5);
            $pdf->Cell($cardWidth, 8, 'Pending', 0, 1, 'C');
            $pdf->SetFont('Times', 'B', 14);
            $pdf->SetXY($startX, $startY + 15);
            $pdf->Cell($cardWidth, 8, number_format($pendingMembers), 0, 1, 'C');
            
            // Card 4: Premium Members
            $startX += $cardWidth + $spacing;
            $pdf->SetFillColor(155, 89, 182);
            $pdf->Rect($startX, $startY, $cardWidth, $cardHeight, 'F');
            $pdf->SetFont('Times', 'B', 10);
            $pdf->SetXY($startX, $startY + 5);
            $pdf->Cell($cardWidth, 8, 'Premium', 0, 1, 'C');
            $pdf->SetFont('Times', 'B', 14);
            $pdf->SetXY($startX, $startY + 15);
            $pdf->Cell($cardWidth, 8, number_format($premiumMembers), 0, 1, 'C');
            
            // Reset position for next section
            $pdf->SetXY(10, $startY + $cardHeight + 15);
            
            // Member Details Header
            $pdf->SetFont('Times', 'B', 12);
            $pdf->SetFillColor(52, 152, 219);
            $pdf->SetTextColor(255, 255, 255);
            $pdf->Cell(0, 8, 'MEMBER DETAILS', 0, 1, 'L', true);
            $pdf->Ln(5);
            
            // Table headers
            $pdf->SetFillColor(52, 73, 94);
            $pdf->SetTextColor(255, 255, 255);
            $pdf->SetFont('Times', 'B', 9);
            $pdf->Cell(10, 8, 'S/No', 1, 0, 'C', true);
            $pdf->Cell(30, 8, 'Name', 1, 0, 'C', true);
            $pdf->Cell(55, 8, 'Email', 1, 0, 'C', true);
            $pdf->Cell(20, 8, 'Status', 1, 0, 'C', true);
            $pdf->Cell(20, 8, 'Role', 1, 0, 'C', true);
            $pdf->Cell(30, 8, 'Joined', 1, 0, 'C', true);
            $pdf->Cell(45, 8, 'Phone', 1, 1, 'C', true);
            
            // Table data
            $pdf->SetTextColor(0, 0, 0);
            $pdf->SetFont('Times', '', 8);
            $serialNumber = 1;
            $rowCount = 0;
            \Log::info('Starting Member Report with ' . count($members) . ' members');
            
            foreach ($members as $index => $member) {
                $currentSerial = $serialNumber + $index;
                \Log::info('Processing member index ' . $index . ', serial_number=' . $currentSerial . ', base_serial=' . $serialNumber . ', name=' . ($member->name ?? 'N/A'));
                
                // Alternate row colors
                if ($rowCount % 2 == 0) {
                    $pdf->SetFillColor(248, 249, 250);
                } else {
                    $pdf->SetFillColor(255, 255, 255);
                }
                
                $pdf->Cell(10, 8, $currentSerial, 1, 0, 'C', true);
                $pdf->Cell(30, 8, substr($member->name, 0, 15), 1, 0, 'L', true);
                $pdf->Cell(55, 8, substr($member->email, 0, 35), 1, 0, 'L', true);
                
                // Status with background color
                $statusColor = [52, 152, 219]; // Default blue
                if ($member->membership_status === 'Active') {
                    $statusColor = [46, 204, 113]; // Green
                } elseif ($member->membership_status === 'Pending') {
                    $statusColor = [241, 196, 15]; // Yellow
                } elseif ($member->membership_status === 'Premium') {
                    $statusColor = [155, 89, 182]; // Purple
                }
                
                $pdf->SetFillColor($statusColor[0], $statusColor[1], $statusColor[2]);
                $pdf->SetTextColor(255, 255, 255);
                $pdf->Cell(20, 8, substr($member->membership_status ?? 'N/A', 0, 8), 1, 0, 'C', true);
                
                $pdf->SetTextColor(0, 0, 0);
                $pdf->SetFillColor($rowCount % 2 == 0 ? 248 : 255, $rowCount % 2 == 0 ? 249 : 255, $rowCount % 2 == 0 ? 250 : 255);
                $pdf->Cell(20, 8, substr(ucfirst($member->role), 0, 8), 1, 0, 'C', true);
                $pdf->Cell(30, 8, date('M d, Y', strtotime($member->created_at)), 1, 0, 'C', true);
                $pdf->Cell(45, 8, substr($member->phone_number ?? 'N/A', 0, 20), 1, 1, 'C', true);
                $rowCount++;
            }
            
            // Footer
            $pdf->SetY(-25);
            $pdf->SetFillColor(52, 152, 219);
            $pdf->SetTextColor(255, 255, 255);
            $pdf->SetFont('Times', 'I', 8);
            $pdf->Cell(0, 8, 'TMCS System - Official Member Report | Confidential', 0, 1, 'C', true);
            
            // Save PDF
            $filename = 'member_report_' . date('Y-m-d_H-i-s') . '.pdf';
            $filepath = public_path('reports/' . $filename);
            
            // Create reports directory if it doesn't exist
            if (!is_dir(public_path('reports'))) {
                mkdir(public_path('reports'), 0777, true);
            }
            
            $pdf->Output('F', $filepath);
            
            return response()->json([
                'success' => true,
                'message' => 'Member report generated successfully',
                'report_url' => asset('reports/' . $filename),
                'filename' => $filename
            ]);
            
        } catch (\Exception $e) {
            \Log::error('Error generating member report: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Error generating report: ' . $e->getMessage()
            ], 500);
        }
    }
    
    public function exportMemberData(Request $request)
    {
        try {
            // Get member data
            $members = User::orderBy('created_at', 'desc')->get();
            
            // Create CSV
            $filename = 'TMCS_Member_Analytics_Report_' . date('Y-m-d_H-i-s') . '.csv';
            $filepath = public_path('reports/' . $filename);
            
            // Create reports directory if it doesn't exist
            if (!is_dir(public_path('reports'))) {
                mkdir(public_path('reports'), 0777, true);
            }
            
            $file = fopen($filepath, 'w');
            
            // Enhanced CSV headers with metadata
            fputcsv($file, ['TMCS SYSTEM - MEMBER ANALYTICS REPORT']);
            fputcsv($file, ['Generated on: ' . date('Y-m-d H:i:s')]);
            fputcsv($file, ['Generated by: ' . Auth::user()->name]);
            fputcsv($file, ['Report ID: TMCS-MR-' . date('YmdHis')]);
            fputcsv($file, []); // Empty row
            
            // Member statistics summary
            $activeMembers = User::where('membership_status', 'Active')->count();
            $newMembers = User::where('created_at', '>=', now()->subDays(30))->count();
            $pendingMembers = User::where('membership_status', 'Pending')->count();
            $premiumMembers = User::where('membership_status', 'Premium')->count();
            $totalMembers = User::count();
            
            fputcsv($file, ['MEMBER STATISTICS SUMMARY']);
            fputcsv($file, ['Metric', 'Value', 'Description']);
            fputcsv($file, ['Total Members', $totalMembers, 'All registered members']);
            fputcsv($file, ['Active Members', $activeMembers, 'Members with active status']);
            fputcsv($file, ['New Members (30 days)', $newMembers, 'Members registered in last 30 days']);
            fputcsv($file, ['Pending Members', $pendingMembers, 'Members awaiting approval']);
            fputcsv($file, ['Premium Members', $premiumMembers, 'Members with premium status']);
            fputcsv($file, []); // Empty row
            
            // Member details headers
            fputcsv($file, ['MEMBER DETAILS']);
            fputcsv($file, ['ID', 'Name', 'Email', 'Phone Number', 'Role', 'Membership Status', 'Registration Number', 'Gender', 'Year of Study', 'Home Diocese', 'Registration Date', 'Created At']);
            
            // CSV data
            foreach ($members as $member) {
                fputcsv($file, [
                    $member->id,
                    $member->name,
                    $member->email,
                    $member->phone_number ?? 'N/A',
                    ucfirst($member->role),
                    $member->membership_status ?? 'N/A',
                    $member->registration_number ?? 'N/A',
                    $member->gender ?? 'N/A',
                    $member->year_of_study ?? 'N/A',
                    $member->home_diocese ?? 'N/A',
                    $member->registration_date ? date('Y-m-d', strtotime($member->registration_date)) : 'N/A',
                    $member->created_at
                ]);
            }
            
            // Footer
            fputcsv($file, []);
            fputcsv($file, ['END OF REPORT']);
            fputcsv($file, ['TMCS System - Official Member Report']);
            fputcsv($file, ['This report is confidential and intended for authorized personnel only']);
            
            fclose($file);
            
            return response()->json([
                'success' => true,
                'message' => 'Member data exported successfully',
                'download_url' => asset('reports/' . $filename),
                'filename' => $filename
            ]);
            
        } catch (\Exception $e) {
            \Log::error('Error exporting member data: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Error exporting data: ' . $e->getMessage()
            ], 500);
        }
    }
}
